### ISSUE TITLE
SRS Ready for Review

### ISSUE THREAD

**Issue by balacij** [balacij/Drasil#11]
[SRS](https://github.com/balacij/Drasil/blob/beamBending/People/Jason/CAS%20741/srs/build/srs.pdf) PDF

Two important caveats:
1. I haven't been able to figure out a general "calculate the reactions at the supports" algorithm yet.
2. I need to plaster citations everywhere (it's mostly the textbook that I borrowed from @smiths and various online resources). 

(also note that I can't assign Mina until she's accepted the invitation to collaborate on this repo, which I've just sent!)

**Comment by samm82** [comment]
Done my review (at least for now 😅)!

**Comment by balacij** [comment]
Thanks @samm82!

**Comment by smiths** [comment]
I'm done my review too @balacij.  My comments are in 236b62efd.  Just like the review for @samm82, I really enjoyed reviewing your SRS.  It has made me think about some things that I previously took for granted.  Great to see another perspective.

**Comment by balacij** [comment]
Thank you very much @smiths :smile:
