### ISSUE TITLE
SRS Review: Issues with Traceability Matrices

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#23]
I didn't go into detail here since Drasil will do this automatically, but each "X" in a matrix represents an _explicit_ reference. Many of these are missing (For example, none of the LCs reference an assumption.)

Minor issue, but Table 6 probably doesn't need to be on its own page.

**Comment by balacij** [comment]
I see what you mean. It's quite difficult to have it added in the manual SRS, I'll lean on Drasil now that we're porting anyway. Thank you!
