### ISSUE TITLE
Issues relate to sections 1,2, and 3:

### ISSUE THREAD

**Issue by MinMah23** [balacij/Drasil#24]
Dear @balacij,
Thank you for your efforts, I enjoy reading your SRS.
These are some comments that I hope make it better. I know that some of them are repeated as Sam mentioned them before and I am sorry, however I try to find the related issues and refer to them.

- [x] The title should start with capital letter and end without period.
- [x] The first two tasks made by Sam on #3.
- [x] I found some " " in different parts of the document which should be revised, such as Beam Bending and increased in the section 2.1.
- [x] As you mentioned in GS2, your tool have two outputs, so it should be added at Figure1 and on the arrow of Output.
- [x] As a part of system context in figure1 and used in IM1, BVP Solvers' responsibilities should be added.
- [x] The arrow between BeamBending and BVP is bidirectional, what data is exchanged between them?
- [x] The first responsibility of the user tells that user should provide assumption. The assumptions of your system are not fixed? user can change them? I think it should be deleted.
- [x] I agree with Sam on issue#9, a general description is preferred.

**Comment by balacij** [comment]
Thank you @MinMah23 ! :smile:  I'm happy to hear that you enjoyed the read!

> The first responsibility of the user tells that user should provide assumption. The assumptions of your system are not fixed? user can change them? I think it should be deleted.

Regarding this point in particular, I mean that the user needs to take the assumptions into consideration when providing input.

**Comment by balacij** [comment]
While going through @samm82's feedback, I think I covered everything here. I will check out the other tickets next.
