### ISSUE TITLE
Address @smiths' feedback for SRS

### ISSUE THREAD

**Issue by balacij** [balacij/Drasil#27]
Just creating this ticket to track my work on addressing @smiths' feedback :)

**Comment by balacij** [comment]
@smiths, thank you very much for your feedback. It definitely improved my document. I switched everything to base SI units as you suggested. Drasil definitely simplifies a lot of work (i.e., unit and description propagation).

Regarding the abstract vs concrete variables, I was trying something 'new' (as we discussed earlier today): having theories rely on 'variable holes' (abstract variables), and then refining those theories to the relevant variables of a 'system' (here, system being the beam bending system). Part of why I'm doing it is so that we can track which variables are treated as being "with respect to a body or thing." If you're not opposed to it, I think it might be helpful. Otherwise, it should be a fairly straightforward fix.

**Comment by smiths** [comment]
Yes, keep your abstract versus concrete variables.  You are on to something, although I'm not sure how it will eventually look.  It does cause confusion when variables appear in the document with the same symbol, but have subtly different meanings.  As you highlight the variable could be for the abstract theory, or it could be for the concrete realization of that theory.

On the Drasil DSL side of things, the more we can keep track of the relationship between the variables the better.  We want to be able to distinguish between a concept and a specific instance of that concept.  (This has come up when we talk about velocity.)  Your distinction between abstract and concrete symbols might eventually be in the Drasil code, but it might not show up as explicitly in the documentation.  Alternatively we might have views of the documentation with an explicit distinction between abstract and concrete and other views that take the traditional engineering documentation approach of leaving the distinction implicit.

**Comment by balacij** [comment]
Thanks @smiths!

I like the idea of using Drasil DSLs to keep track of the variable relationships. I have no idea where to begin, but I hope this is a start to figuring that out. I hope this is fruitful :smile:
