### ISSUE TITLE
VnV Ready for Review

### ISSUE THREAD

**Issue by balacij** [balacij/Drasil#28]
I just have to add Deesha to the repo too, but I'll assign her too.

One caveat is that I didn't mention any units in this document. I need to make a choice and fix my SRS first, and then I will update this document.

Another caveat is the abstract vs concrete symbols. I haven't changed them (yet) -- I will send @smiths a message about it soon!

**Comment by smiths** [comment]
Sounds good @balacij.

**Comment by samm82** [comment]
Done my review!

**Comment by balacij** [comment]
That was quick! Thank you @samm82 :smile:

**Comment by DeeshaPatel** [comment]
I have done my review! You did a great job!

**Comment by balacij** [comment]
Thank you @DeeshaPatel! :smile:

**Comment by smiths** [comment]
I've done my review too.  The comments are in the attached pdf file.

[plan-Fdbck.pdf](https://github.com/balacij/Drasil/files/10856371/plan-Fdbck.pdf)

**Comment by balacij** [comment]
Thank you very much, @smiths :smile:
