### ISSUE TITLE
VnV Plan Review: Unit Test Description section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#36]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] This section doesn't need to be on a new page.
- [x] What do you mean by "we will bootstrap the Drasil-generated software artifacts for testing"?

**Comment by balacij** [comment]
Thanks! I clarified in 6d119470a

Re. new page: it helps when editing on a tablet. In general, I like having page breaks for the extra whitespace given to commenters.

**Comment by samm82** [comment]
ooh good call lol
