### ISSUE TITLE
VnV Plan review: Some basic comments

### ISSUE THREAD

**Issue by DeeshaPatel** [balacij/Drasil#38]
- [x] In your general Information section (3) you wrote "Plan of action" - I guess this is a wordy statement. 
- [x] In section 4.7 (Software validation plan) Last statement "Input, output, ..." is ambiguous. 
- [x] In table 3: you wrote "Simple, Automatic, Tests" for table caption. Is it intentional? I guess "," (Comma) is not required. 
- [ ] I found one infinity sign outside of the table 3. You can place it somewhere.

**Comment by DeeshaPatel** [comment]
Also, my one suggestion is that you can add link or may be give reference to the "SRS checklist". (NOT required) but it's good to have.

**Comment by balacij** [comment]
Re. infinity: Ah, do you mean the page number? The page is oriented in landscape mode.

I'll close this ticket for now, I've completed the majority of it, thank you! bd8559b94
