### ISSUE TITLE
VnV Plan review: Implementation Verification Plan

### ISSUE THREAD

**Issue by DeeshaPatel** [balacij/Drasil#39]
Comment for your section 4.5, 

It looks like you have focused highly on "How implementation will done?" I think you can highlight it. But mainly, you should focus on plan for implementation testing. For example, you can give more details about how you can perform code walkthrough and who will take participation in it? Or How you will conduct peer review?

**Comment by balacij** [comment]
Thank you! I fixed this in 46d155c03
