### ISSUE TITLE
SRS Review: "BeamBending" in Abbreviations and Acronyms section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#4]
Not only is "BeamBending" neither an abbreviation nor an acronym, but, if included here, its description is not particularly informative.

**Comment by balacij** [comment]
In Dr. Smith's review, he mentioned I should add "Program" to the end of the description, which I think makes it more informative. I'll try to think of a better abbreviation for BeamBending -- I've been thinking about renaming it for a while, I just haven't come up with a better name.
