### ISSUE TITLE
VnV Plan review: Tests for non-function requirement

### ISSUE THREAD

**Issue by DeeshaPatel** [balacij/Drasil#40]
In your section 5.2,

Again, it looks like lack of testing plan. I guess you can give more and accurate details about non-functional tests by concentrating "How you can get confident that you achieved it?"

**Comment by balacij** [comment]
Thank you, I tried to clarify further. I defer a lot of the 'confidence' gathering work to Drasil using a 'verified by construction' approach. 8810d8e78 Please let me know if you think I should further clarify! :smile:

**Comment by DeeshaPatel** [comment]
Sounds good to me. :)
