### ISSUE TITLE
VnV Plan review: Functional requirement

### ISSUE THREAD

**Issue by DeeshaPatel** [balacij/Drasil#42]
Your section 5.1.1 to 5.1.3 are too confusing. 

Reasons: 

- [x] - I guess you wrote two subcategories of 5.1.1 are 5.1.2 and 5.1.3. - So, it should be either sub sub categories.  
- [x] - Also, same table for both subcategories make it even more confusing. - I think you should separate it for different subcategories.
- [x] - How testing for "testing output with non-trivial inputs" is performed? - It's not clear. 

You can work on it to make it better.

**Comment by balacij** [comment]
Thank you, I have clarified it a bit more! 726e3e23c
