### ISSUE TITLE
Use `tmNoRefs` if sources aren't relevant for a TM

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#47]
I noticed your comments in TheoryModels.hs:

https://github.com/balacij/Drasil/blob/a80ca2444bb6b35251ab9d1a019f83c96c6906a4/code/drasil-example/bmbnd/lib/Drasil/BmBnd/TheoryModels.hs#L21

Note that you don't need a source if you use the `tmNoRefs` constructor. This implementation forces the user to explicitly decide if they want to include a source instead of naively passing in an empty list to just try to get a minimal viable product and potentially leave a TM unsourced.

(Feel free to either use `tmNoRefs` or keep your current "placeholder" sources; this just seemed like the best way to let you know lol)

**Comment by balacij** [comment]
Ah, thank you! I found it a bit odd that the restriction for having a 'source'/'ref' was required for one smart constructor but not for the other, even when they're both expected to give us `TheoryModel`s in the end!
