### ISSUE TITLE
Drasil SRS Code Review

### ISSUE THREAD

**Issue by balacij** [balacij/Drasil#48]
The Drasil SRS code is ready for review. I focused on building on code generation, but failed by the end of the March 29th deadline. Hopefully I'll be able to make some progress on it before the end of the course, but definitely before the summer. I've created several tickets on the main Drasil repository `JacquesCarette/Drasil.git`, and I'll be creating more as I go along.

All code relevant to my attempts were mentioned in my presentation on Thursday March 30th and are public (on the [`beamBending`](https://github.com/balacij/Drasil/tree/beamBending) and [`bmBndngNoFunctions`](https://github.com/balacij/Drasil/tree/bmBndngNoFunctions) branches, deviating at the type of `y_B` [the deflection _function_] being a function, or a vector -- which is what Drasil prefers for the code generation). On both branches, the artifacts can be found in the [stable](https://github.com/balacij/Drasil/tree/bmBndngNoFunctions/code/stable/bmbnd) folder, and the source code can be found in the [`drasil-examples` folder](https://github.com/balacij/Drasil/tree/bmBndngNoFunctions/code/drasil-example/bmbnd).

The original SRS is also [available](https://github.com/balacij/Drasil/blob/bmBndngNoFunctions/People/Jason/CAS%20741/srs/build/srs.pdf) and will likely need to be used for reference.

* [x] @smiths 
* [x] @samm82 
* [x] @Maryamvalian

**Comment by samm82** [comment]
@smiths @balacij Where would the best place be to keep track of issues that are specific to Drasil (e.g., something in the SRS is rendered weirdly that is likely a problem with Drasil and not this SRS specifically)? I was thinking about creating them here and adding a `drasil-specific` tag; should they just be made on the Drasil repo itself?

**Comment by samm82** [comment]
I mainly focused my review on what was done on the SRS, since I know that there is more to do and that code generation isn't working yet.

**Comment by smiths** [comment]
> @smiths @balacij Where would the best place be to keep track of issues that are specific to Drasil (e.g., something in the SRS is rendered weirdly that is likely a problem with Drasil and not this SRS specifically)? I was thinking about creating them here and adding a `drasil-specific` tag; should they just be made on the Drasil repo itself?

I think we should create the Drasil specific issues in the main Drasil repo.

**Comment by samm82** [comment]
Sorry for the delay, but I've just created https://github.com/JacquesCarette/Drasil/issues/3341 and https://github.com/JacquesCarette/Drasil/issues/3342 based on observations of BeamBending; I've got a slew of issues that I will be creating based on ChemCode eventually 😅

**Comment by smiths** [comment]
@balacij my feedback is in the attached pdf.  I believe some of it repeats issues that you and @samm82 are already discussing.
[BmBnd_SRS_Fdbck.pdf](https://github.com/balacij/Drasil/files/11225931/BmBnd_SRS_Fdbck.pdf)

**Comment by balacij** [comment]
Thank you very much @smiths :smile:
