### ISSUE TITLE
Discrepancy between w and w_B

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#51]
Throughout the table of symbols, a symbol with the subscript "B" seems to indicate that it is the concrete version of the quantity:
![image](https://user-images.githubusercontent.com/35857611/229612286-ad7a58ea-5ec2-45fa-a0cb-babdd9cef45c.png)
![image](https://user-images.githubusercontent.com/35857611/229612307-cba4ffcd-95d2-486a-a1a3-27b4216f4959.png)

However, $w$ and $w_B$ seem to break this pattern.

![image](https://user-images.githubusercontent.com/35857611/229612392-8ad42180-76ea-4feb-9998-c20b4a220c29.png)

While this isn't necessarily an issue, I just wanted to make sure this was intentional

**Comment by balacij** [comment]
Thanks! I fixed this now in 01a60ca11c431183fdf6fdc5054d217b494159ba .
