### ISSUE TITLE
"Load" vs. "Loading"

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#60]
I notice the words "load" and "loading" come up repeatedly and am just wondering if there is a semantic difference between the two.

**Comment by smiths** [comment]
I like the way you think @samm82.  You question everything, even the little things.  :smile:  I doubt @balacij intended any semantic difference between the two terms.  My guess is the term that sounded best in a given context is the one that was selected.  Both load and loading can be verbs and nouns, so there isn't a distinction to be made there.

If we look at the [Strength of Materials/ Loading of Beams](https://en.wikibooks.org/wiki/Strength_of_Materials/Loading_of_Beams#:~:text=The%20loads%20on%20a%20beam,the%20kind%20of%20support%20used.) webpage we see both terms used.  I read over it trying to distinguish a pattern, but I haven't come up with anything better than load sounds right some times, and loading sounds better at other times.  :smile:

**Comment by samm82** [comment]
I think what I would do then is to have "load/loading" or "load(ing)" in the Terminology section to capture that they are synonyms

**Comment by balacij** [comment]
Thank you both. As @smiths mentioned, I was only using the variant that sounded best contextually. I've added the synonym to the terminology section now :smile: e49e5a635047a7cccd7c0986ef551c035819e49b
