### ISSUE TITLE
Add check for empty Likely Changes section to mirror check for empty Unlikely changes section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#61]
As mentioned in https://github.com/balacij/Drasil/commit/e5af4bfdf741b6e0c9d19eaa0f8ddae913b4093d#r107392054.

Noted in the comment below, this should likely be done for other sections as well, but I specifically point out this issue to improve the consistency and leave the rest to your discretion.

_I just made this an issue to be explicit about it so we don't lose it lol_

**Comment by balacij** [comment]
Duplicate of #57?

**Comment by balacij** [comment]
I'll also need to make a separate PR for these core changes to Drasil too.

**Comment by samm82** [comment]
Oops; I'm tired 😅

**Comment by balacij** [comment]
No problem :smile:
