### ISSUE TITLE
Section 7 Unlikely changes

### ISSUE THREAD

**Issue by Maryamvalian** [balacij/Drasil#62]
I think section 7 should not be empty. you have mentioned that "There are no unlikely changes". May be I'm wrong but I think the goal of this software, which is examining a beam bending under load is unlikely to change. otherwise there will completely another software, and not a new version of this software.

**Comment by balacij** [comment]
That is correct :smile: Thank you. https://github.com/balacij/Drasil/commit/f90e9739f3d826625c0ecadeda6eb573d86ceefc
