### ISSUE TITLE
A11 :The beam is simply supported

### ISSUE THREAD

**Issue by Maryamvalian** [balacij/Drasil#63]
A11 seems ambiguous to me. Maybe I'm wrong but I think you mean that the support is pinned or roller. In this case, I think you should complete your sentence.

**Comment by balacij** [comment]
I believe that the definition of 'simply supported' includes that one of the supports must be pinned and the other must be a roller. Does this suffice? I have the phrase defined in my table of definitions.

**Comment by smiths** [comment]
Yes, simply supported is a standard term for a beam.  Your definition is correct @balacij.

**Comment by balacij** [comment]
Ah, thank you @smiths. In that case, I'll close the ticket. Please let me know if there is any other issue @Maryamvalian
