### ISSUE TITLE
SRS Review: Correct User Characteristics?

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#9]
Related to https://github.com/balacij/Drasil/issues/6; I'm not sure if "the user of this software should be a civil engineer or equivalent," since the user of the software could be more general than that. An engineering firm might have a co-op student that they get to do some simulations and make a presentation on to get some alternatives for licensed engineering to independently evaluate (assuming that this is something that could happen in practice).

**Comment by balacij** [comment]
Thanks! I think I fixed this in 4a3490fb3adff54d62dc9d50766cb13f05c723c2
